name: Upload Instagram Reel

on:
  schedule:
    # 6:00 PM IST
    - cron: '30 12 * * *'

    # 12:00 AM IST
    - cron: '30 18 * * *'

    # 1:00 AM IST
    - cron: '30 19 * * *'

    # 3:00 AM IST
    - cron: '30 21 * * *'

  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Reel Upload Script
        env:
          GOOGLE_TOKEN: ${{ secrets.GOOGLE_TOKEN }}

          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

          IG_ACCESS_TOKEN: ${{ secrets.IG_ACCESS_TOKEN }}
          IG_ID: ${{ secrets.IG_ID }}

          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}

        run: python script.py
